### ISSUE TITLE
map_serverがインストールされていない時点で地図保存コマンドが説明されている

### ISSUE THREAD

**Issue by atinfinity** [vstoneofficial/megarover_samples#10]
[ROS 対応 3D シミュレーターモデル メガローバー版 取扱説明書(2020.03.24)](http://vstone.co.jp/products/wheelrobot/pdf/megarover_ros_simulator.pdf)だと地図保存コマンドとして

```
rosrun map_server map_saver -f ファイル名
```

というコマンドの記載がありますが、現状の説明書の手順通りにセットアップするとmap_serverのパッケージが入っていないように見受けられます。

**Comment by matsuyama-v** [comment]
ご指摘いただきありがとうございます。
対応が大変遅くなり申し訳ございません。

ドキュメントを修正し、事前にmap_serverをインストールするよう記述を加えました。
[ROS 対応 3D シミュレーターモデル メガローバー版 取扱説明書(2021.01.06)](http://vstone.co.jp/products/wheelrobot/pdf/megarover_ros_simulator.pdf)
