### ISSUE TITLE
ROS2対応予定

### ISSUE THREAD

**Issue by atinfinity** [vstoneofficial/megarover_samples#4]
本リポジトリはROS1のみ対応しているという認識です。今後ROS2対応の予定はありますか？

**Comment by matsuyama-v** [comment]
現時点では明確な対応予定はありません。
本体側のファームウェアも含めて、大型台車シリーズとしてどのような形で対応すべきか検討している段階です。

**Comment by atinfinity** [comment]
@matsuyama-v ご回答ありがとうございました。現状の状況理解できました。

**Comment by atinfinity** [comment]
@matsuyama-v Gazebo環境のみですが地図生成、ナビゲーションをROS2化しました。
<https://github.com/atinfinity/megarover_samples_ros2>

その際、このプロジェクトのモデルファイル（xacro、URDFファイルなど）やworldファイルを使用させて頂きました。

## 地図生成

![image](https://user-images.githubusercontent.com/2630323/110875670-695c2680-8319-11eb-960b-1a9b4ba7b9b1.png)

## ナビゲーション

![image](https://user-images.githubusercontent.com/2630323/110875701-78db6f80-8319-11eb-938f-8ec0ea0ef892.png)
